apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensourceteam9-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opensourceteam9
  template:
    metadata:
      labels:
        app: opensourceteam9
    spec:
      containers:
      - name: opensourceteam9-container
        image: 20221157/team9:latest # Docker Hub 계정 반영
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: opensourceteam9-service
spec:
  selector:
    app: opensourceteam9
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

